---
- include: config.yml

- name: resload systemd
  sudo: yes
  command: systemctl daemon-reload

- name: enable consul
  become: yes
  service:
    name: consul
    enabled: yes
    state: started
  notify:
    - restart consul
  tags:
    - consul

- name: wait for consul to listen
  wait_for:
    host: "{{ consul_bind_addr }}"
    port: 8500
